### ISSUE TITLE
This is straight up fake and most likely malware.

### ISSUE THREAD

**Issue by deadtown** [n003rron/StalcraftNoeron#1]
After looking into this, there are so many hpp files that access undeclared namespaces as well as the files including header files that don't even exist. This is pasted code to hide the fact that loader.exe is most likely malware.

**Comment by SeksMachina** [comment]
thank you so much, i will trust you then. Wasnt sure if it was legit and im a complete retard so you prob saved me. Do you maybe know other cheats that are legit?

**Comment by deadtown** [comment]
No, this game is dead, there arent any cheats for this that are public.
